spring:
  data:
    redis:
      host:
      port:
      username:
      password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
